server:
  port: 8085
mybatis:
  type-aliases-package: com.topone.emptest.domain
  mapper-locations: classpath:com/topone/emptest/mapper/*.xml


spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1:3306/newertu?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
